FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-streamlit.txt /app/requirements-streamlit.txt
RUN pip install --no-cache-dir -r /app/requirements-streamlit.txt

COPY app /app/app

EXPOSE 8501

CMD ["streamlit", "run", "/app/app/main.py", "--server.address=0.0.0.0", "--server.port=8501", "--client.toolbarMode=minimal"]
